services:
  - type: web
    name: wedding-website
    runtime: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: COUPLE_EMAIL
        value: wong.jennicaarah@gmail.com
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
